# Generated by Django 5.0 on 2026-09-04 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=120)),
                ('tagline', models.CharField(max_length=200)),
                ('problem', models.TextField()),
                ('features', models.JSONField(default=list)),
                ('metrics', models.JSONField(default=list)),
                ('stack', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=80)),
                ('year', models.PositiveIntegerField()),
                ('screenshot', models.ImageField(blank=True, upload_to='projects/')),
                ('github_url', models.URLField(blank=True)),
                ('live_url', models.URLField(blank=True)),
                ('category', models.CharField(choices=[('fullstack', 'Full-Stack'), ('ai', 'AI'), ('writing', 'Writing')], default='fullstack', max_length=20)),
                ('featured', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', '-year'],
            },
        ),
        migrations.CreateModel(
            name='SiteMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Meshack Mbithi', max_length=80)),
                ('headline', models.CharField(default='Full-Stack Engineer · AI Quality Specialist', max_length=200)),
                ('location', models.CharField(default='Nairobi, KE · GMT+3', max_length=80)),
                ('status', models.CharField(default='Open to contract & full-time remote roles', max_length=200)),
                ('email', models.EmailField(default='meshackmbithi01@gmail.com', max_length=254)),
                ('phone', models.CharField(default='0794913356', max_length=40)),
                ('bio_short', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Site Meta',
            },
        ),
    ]
