# Generated by Django 5.0 on 2026-09-05 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitemeta',
            name='cv',
            field=models.FileField(blank=True, upload_to='cv/'),
        ),
        migrations.AddField(
            model_name='sitemeta',
            name='github_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='sitemeta',
            name='linkedin_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='sitemeta',
            name='skills',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='sitemeta',
            name='twitter_url',
            field=models.URLField(blank=True),
        ),
    ]
