# Generated by Django 5.0 on 2026-09-05 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_sitemeta_cv_sitemeta_github_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitemeta',
            name='facebook_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='sitemeta',
            name='instagram_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='sitemeta',
            name='whatsapp_url',
            field=models.URLField(blank=True),
        ),
    ]
