# Generated by Django 5.0 on 2026-09-05 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_sitemeta_facebook_url_sitemeta_instagram_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('ai', 'AI Engineering'), ('fullstack', 'Full-Stack Web')], default='fullstack', max_length=20),
        ),
        migrations.AlterField(
            model_name='sitemeta',
            name='headline',
            field=models.CharField(default='AI Engineer · Full-Stack Developer', max_length=200),
        ),
    ]
